In [1]:
from mnist_classifier import *
from mnist_data import *
import numpy as np
import random

Using TensorFlow backend.


In [2]:
cls = MnistClassifier()
d = MnistData(use_data_subset = True)

## Train Mnist Classifier on all data

In [3]:
cls.fit(*d.into_fit())

Train on 6000 samples, validate on 1000 samples
Epoch 1/1
6000/6000 [==============================] - 13s 2ms/step - loss: 0.9745 - acc: 0.6810 - val_loss: 0.3648 - val_acc: 0.8980


In [4]:
cls.evaluate(*d.into_evaluate())

1000/1000 [==============================] - 1s 581us/step
Test loss: 0.3647724571228027
Test accuracy: 0.898


[0.3647724571228027, 0.898]

## Train Mnist Classifier on all data but class 5

In [5]:
# get n_classes from data object. no more global constants
n_classes = d.get_num_classes()

# we'll just use 5
d.set_removed_class(5, verbose=True)

current number of examples per digit -- train:
 {0: 592, 1: 671, 2: 581, 3: 608, 4: 623, 6: 608, 7: 651, 8: 551, 9: 601}

current number of examples per digit -- test:
 {0: 85, 1: 126, 2: 116, 3: 107, 4: 110, 6: 87, 7: 99, 8: 89, 9: 94}


In [6]:
cls.fit(*d.into_fit())

Train on 5486 samples, validate on 913 samples
Epoch 1/1
5486/5486 [==============================] - 12s 2ms/step - loss: 0.8754 - acc: 0.7147 - val_loss: 0.3078 - val_acc: 0.9014


In [7]:
cls.evaluate(*d.into_evaluate())

1000/1000 [==============================] - 1s 697us/step
Test loss: 0.28098332381248475
Test accuracy: 0.825


[0.28098332381248475, 0.825]

## Train using n samples of the class removed

In [8]:
cls.fit(*d.into_fit(n = 20))

Train on 5506 samples, validate on 1000 samples
Epoch 1/1
5506/5506 [==============================] - 12s 2ms/step - loss: 0.8685 - acc: 0.7134 - val_loss: 0.4107 - val_acc: 0.7780


In [9]:
cls.evaluate(*d.into_evaluate())

1000/1000 [==============================] - 1s 570us/step
Test loss: 0.4107179440259933
Test accuracy: 0.778


[0.4107179440259933, 0.778]

## Train using n samples + generated data

In [10]:
generated_data = d.get_generated_data_stub()
cls.fit(*d.into_fit(n = 20, generated_data = generated_data))

Train on 5556 samples, validate on 1000 samples
Epoch 1/1
5556/5556 [==============================] - 11s 2ms/step - loss: 0.8881 - acc: 0.7009 - val_loss: 0.3482 - val_acc: 0.8230


In [11]:
cls.evaluate(*d.into_evaluate())

1000/1000 [==============================] - 1s 571us/step
Test loss: 0.3481994481086731
Test accuracy: 0.823


[0.3481994481086731, 0.823]

## To Low Shot Dataset Method

In [4]:
lsds = d.to_low_shot_dataset(verbose=True)

Note class removed paramater was overriden. re-Run d.set_removed_class() if needed


## Generator Benchmark

In [1]:
from mnist_classifier import *
from mnist_data import *
import numpy as np
import random
from generator import *

cls = MnistClassifier
d = MnistData(use_data_subset = True)

Using TensorFlow backend.


In [ ]:
LowShotGenerator.benchmark(Classifier=cls, 
                           data_object=d,
                           dataset_name='mnist',
                           n_clusters=10,
                           λ = 0.5)

done :tada: dataset for quadruplets data collection saved as *mnist_for_collection*
Creating clusters/centroids by 1 jobs
Running KMeans to get 10 clusters/centroids for `5`.
Running KMeans to get 10 clusters/centroids for `0`.
Running KMeans to get 10 clusters/centroids for `4`.
Running KMeans to get 10 clusters/centroids for `1`.
Running KMeans to get 10 clusters/centroids for `9`.
Running KMeans to get 10 clusters/centroids for `2`.
Running KMeans to get 10 clusters/centroids for `3`.
Running KMeans to get 10 clusters/centroids for `6`.
Running KMeans to get 10 clusters/centroids for `7`.
Running KMeans to get 10 clusters/centroids for `8`.
done to cluster :tada: centroids saved as *mnist_centroids_10_clusters*
current number of examples per digit -- train:
 {0: 592, 1: 671, 2: 581, 3: 608, 4: 623, 5: 514, 6: 608, 7: 651, 8: 551, 9: 601}

current number of examples per digit -- test:
 {0: 85, 1: 126, 2: 116, 3: 107, 4: 110, 5: 87, 6: 87, 7: 99, 8: 89, 9: 94}
Train on 6000 samples, v

(Pdb) self.x_train
*** AttributeError: 'MnistClassifier' object has no attribute 'x_train'
(Pdb) self.predict([x_test[0]])
*** ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (28, 28, 1)
(Pdb) self.predict(x_test)
array([[1.12613803e-02, 7.20420721e-05, 3.80838246e-05, 4.70855413e-03,
        4.31079621e-04, 9.64292586e-01, 6.95284165e-04, 1.86667719e-04,
        1.76550504e-02, 6.59167883e-04],
       [7.23092025e-03, 6.07125767e-05, 3.12057855e-05, 5.78691252e-03,
        2.81078246e-04, 9.72521544e-01, 4.30848944e-04, 1.18595883e-04,
        1.31044975e-02, 4.33595415e-04],
       [1.09370770e-02, 3.69861918e-05, 3.19252576e-05, 4.17025480e-03,
        2.15882945e-04, 9.60908353e-01, 3.68521025e-04, 1.25073173e-04,
        2.27686297e-02, 4.37159033e-04],
       [8.68128985e-03, 5.05191892e-05, 2.51586807e-05, 3.77907511e-03,
        3.05109046e-04, 9.71655846e-01, 4.71131410e-04, 1.33895795e-04,
        1.44616077e-02, 4

(Pdb) np.argmax(self.predict(x_test))
993
(Pdb) np.argmax(self.predict(x_test), axis=0)
array([34, 75, 77, 99, 31, 12, 34, 56, 24, 64])
(Pdb) np.argmax(self.predict(x_test), axis=1)
array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 5, 8, 8, 5, 5, 5, 5, 5, 5, 3, 5, 5,
       5, 5, 5, 5, 5, 5, 8, 8, 5, 8, 8, 8, 8, 8, 8, 8, 3, 3, 3, 3, 8, 3,
       5, 5, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])


In [ ]:
self.x_train